import telebot
import os
import time
from src.bot.pref_manager import get_user_preference
from src.utils.image_generator import generate_betting_card, generate_accumulator_card

# Global bot instance to avoid re-initializing
_bot_instance = None

def get_bot():
    global _bot_instance
    if _bot_instance is None:
        token = os.getenv("TELEGRAM_BOT_TOKEN")
        if not token:
            return None
        _bot_instance = telebot.TeleBot(token)
    return _bot_instance

def deliver_prediction(chat_id, match_data, retries=2):
    """
    Routes a single prediction to a user based on their preferred delivery mode.
    """
    bot = get_bot()
    if not bot:
        print("❌ TELEGRAM_BOT_TOKEN missing in environment.")
        return False

    mode = get_user_preference(chat_id)
    match_name = match_data.get("match", "Unknown Match")
    
    # Extract pick details
    sc = match_data.get("supreme_court", {})
    av = match_data.get("audit_verdict", {})
    
    pick_tip = "N/A"
    odds = "0.00"
    
    if sc and sc.get("primary_safe_pick"):
        pick_tip = sc["primary_safe_pick"].get("tip", "N/A")
        odds = sc["primary_safe_pick"].get("odds", "0.00")
    elif av and av.get("ai_recommended_bet"):
        pick_tip = av.get("ai_recommended_bet", "N/A")
        odds = av.get("estimated_odds", "0.00")
    else:
        pick_tip = match_data.get("primary_pick", {}).get("tip", match_data.get("safe_bet_tip", "N/A"))
        odds = match_data.get("primary_pick", {}).get("odds", match_data.get("confidence", "0.00"))

    if mode == 'image':
        for attempt in range(retries + 1):
            try:
                image_path = generate_betting_card(match_data)
                caption = f"🏆 *{match_name}*\n⚖️ Supreme Court Verdict: *{pick_tip}*\n📈 Odds: *{odds}*"
                with open(image_path, 'rb') as photo:
                    bot.send_photo(chat_id, photo, caption=caption, parse_mode='Markdown', timeout=20)
                return True
            except Exception as e:
                print(f"⚠️ Attempt {attempt + 1} failed sending image: {e}")
                if attempt < retries:
                    time.sleep(1)
                    continue
                else:
                    mode = 'text'

    if mode == 'text':
        try:
            text = (
                f"🔥 *OMNIBET AI PREDICTION* 🔥\n\n"
                f"⚽ *Match:* {match_name}\n"
                f"⚖️ *Supreme Court Verdict:* _{pick_tip}_\n"
                f"📈 *Odds:* `{odds}`\n\n"
                f"🔗 _Analyze more at OmniBet AI Dashboard_"
            )
            bot.send_message(chat_id, text, parse_mode='Markdown', timeout=10)
            return True
        except Exception as e:
            print(f"❌ Error sending text prediction: {e}")
            return False

    return False

def deliver_accumulator(chat_id, bets, total_odds, retries=2):
    """
    Delivers a consolidated multi-bet prediction.
    """
    bot = get_bot()
    if not bot:
        return False

    mode = get_user_preference(chat_id)
    
    if mode == 'image':
        for attempt in range(retries + 1):
            try:
                image_path = generate_accumulator_card(bets)
                caption = f"🔥 *ELITE ACCUMULATOR* 🔥\n📊 Matches: {len(bets)}\n📈 Total Odds: *{total_odds:.2f}x*\n\n🚀 _Join the winning side with OmniBet AI_"
                with open(image_path, 'rb') as photo:
                    bot.send_photo(chat_id, photo, caption=caption, parse_mode='Markdown', timeout=30)
                return True
            except Exception as e:
                print(f"⚠️ Accumulator image attempt {attempt + 1} failed: {e}")
                if attempt < retries:
                    time.sleep(1)
                    continue
                else:
                    mode = 'text'

    if mode == 'text':
        try:
            text = f"🔥 *OMNIBET AI ACCUMULATOR* 🔥\n\n"
            for bet in bets:
                text += f"⚽ *{bet.get('match', 'Match')}*\n⚖️ Pick: _{bet.get('selection', 'N/A')}_ | Odds: `{bet.get('odds', '0.00')}`\n\n"
            text += f"💰 *Total Odds: {total_odds:.2f}x*\n\n"
            text += "⚡ _Generated by OmniBet AI Engine_"
            bot.send_message(chat_id, text, parse_mode='Markdown', timeout=15)
            return True
        except Exception as e:
            print(f"❌ Error sending consolidated text: {e}")
            return False

    return False
